language: node_js
node_js:
- stable
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn test
- yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github_token: "$github_token"
  local-dir: build
  committer-from-gh: true
  on:
    branch: master
notifications:
  webhooks: https://www.travisbuddy.com/
