language: node_js
node_js:
- stable
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn test
# - yarn build # skip this step until I can fix the authentication issue
deploy:
  provider: pages
  token: $github_token
  local_dir: build
  edge: true #opt in dpl v2
  on:
    branch: master
notifications:
  webhooks: https://www.travisbuddy.com/
