name: Build CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: yarn

  test:
    name: Test
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: yarn test

  deploy:
    name: Build and Deploy
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Build and Deploy
        run: yarn deploy
