name: Build CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test_and_deploy:
    name: Test and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: yarn

      - name: Test
        run: yarn test
